### ISSUE TITLE
TypeError: a.data.split is not a function

### ISSUE THREAD

**Issue by scrimpy** [oneall/social-login-whmcs#1]
library.js?lang=de:formatted:931 Uncaught TypeError: a.data.split is not a function
    at d.xd_parser (library.js?lang=de:formatted:931)
    at d.xd_listener (library.js?lang=de:formatted:940)
    at library.js?lang=de:formatted:554
    at c (library.js?lang=de:formatted:177)
xd_parser @ library.js?lang=de:formatted:931
xd_listener @ library.js?lang=de:formatted:940
(anonymous) @ library.js?lang=de:formatted:554
c @ library.js?lang=de:formatted:177
postMessage (async)
PostMessageStream._write @ contentscript.js:3467
doWrite @ contentscript.js:5409
writeOrBuffer @ contentscript.js:5398
Writable.write @ contentscript.js:5325
ondata @ contentscript.js:4390
EventEmitter.emit @ contentscript.js:2505
addChunk @ contentscript.js:4062
readableAddChunk @ contentscript.js:4049
Readable.push @ contentscript.js:4016
PortDuplexStream._onMessage @ contentscript.js:161
EventImpl.dispatchToListener @ VM1126 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM1132 extensions::utils:138
EventImpl.dispatch_ @ VM1126 extensions::event_bindings:387
EventImpl.dispatch @ VM1126 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM1132 extensions::utils:138
dispatchOnMessage @ VM1133 extensions::messaging:392

**Comment by scrimpy** [comment]
xd_parser: function(a) {
        if ("undefined" !== typeof a.data && (a = a.data.split("::"),
        2 === a.length)) {
            var b = parseInt(a[0], 10);
            if (b === this.id)
                return a = a[1],
                a = a.split("|")
        }
    },

**Comment by scrimpy** [comment]
i can log in without this error, but after this login i receive only errors anymore and the login is not possible anymore.
is it some cache error or something?

**Comment by SchlesserClaude** [comment]
Hello,

this seems to be a compatibility issue with another script on your page.
Could you please post a link to your website? I will have a closer look.

Regards,

**Comment by jaroslavstreit** [comment]
This is not resolution of this problem. We've got same:
`Uncaught TypeError: a.data.split is not a function

    at d.xd_parser (library.js?lang=cs:62)
    at d.xd_listener (library.js?lang=cs:62)
    at library.js?lang=cs:39
    at c (library.js?lang=cs:13)`
